# -*- coding: utf-8 -*-
"""Cancer_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQZNP09CbwMGQ2xiwlGjQZO8AF4OttMj
"""

import pandas as pd

# Load GEO expression file
data = pd.read_csv(
    "/content/GSE2034_series_matrix (1).txt",
    sep="\t",
    comment="!"
)

# Show first rows
print(data.head())

# Show dimensions
print(data.shape)

comment="!"

# Remove empty rows
data = data.dropna()

# Set gene column as index
data = data.set_index("ID_REF")

print(data.head())

data = data.T

print(data.head())

print(data.shape)

data = data.apply(pd.to_numeric, errors='coerce')
data = data.dropna(axis=1, how='all')

data = data.fillna(0)

labels = [
    "Tumor",
    "Tumor",
    "Normal",
    "Normal"
]

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(labels)

from sklearn.model_selection import train_test_split

X = data
y = labels

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = data

original_labels = labels
# Calculate how many times to repeat the original_labels to match X's sample count
num_repeats = (X.shape[0] + len(original_labels) - 1) // len(original_labels)
expanded_labels = (original_labels * num_repeats)[:X.shape[0]]

# Encode the expanded labels
encoder = LabelEncoder()
y = encoder.fit_transform(expanded_labels)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy on the test set: {accuracy:.4f}")

print("Classification Report:")
print(classification_report(y_test, y_pred))

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialize and train a Logistic Regression model
log_reg_model = LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')
# Increased max_iter for convergence
log_reg_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_log_reg = log_reg_model.predict(X_test)

# Evaluate the model
accuracy_log_reg = accuracy_score(y_test, y_pred_log_reg)
print(f"Accuracy on the test set (Logistic Regression): {accuracy_log_reg:.4f}")
print("\nClassification Report (Logistic Regression):")
print(classification_report(y_test, y_pred_log_reg))

predictions = model.predict(X_test)

import matplotlib.pyplot as plt
import seaborn as sns

feature_importances = model.feature_importances_

# Create a DataFrame for better visualization
features_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': feature_importances
})

# Sort features by importance in descending order
features_df = features_df.sort_values(by='Importance', ascending=False)

# Display the top 20 most important features (genes)
print("Top 20 Most Important Genes:")
display(features_df.head(20))

# Plot the top 20 most important features
plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=features_df.head(20), hue='Feature', palette='viridis', legend=False)
plt.title('Top 20 Most Important Genes for Classification')
plt.xlabel('Feature Importance')
plt.ylabel('Gene ID (ID_REF)')
plt.tight_layout()
plt.show()

top_20_genes = features_df.head(20)['Feature'].tolist()

X_top_genes = X[top_20_genes]
y_series = pd.Series(y, name='Target_Label', index=X.index)
correlation_df = pd.concat([X_top_genes, y_series], axis=1)
correlation_matrix = correlation_df.corr(method='pearson')
gene_target_correlations = correlation_matrix['Target_Label'].drop('Target_Label')

print("Correlation of Top 20 Genes with Target Label:")
display(gene_target_correlations.sort_values(ascending=False))

plt.figure(figsize=(10, 8))
sns.barplot(x=gene_target_correlations.values, y=gene_target_correlations.index, hue=gene_target_correlations.index, palette='coolwarm', legend=False)
plt.title('Correlation of Top 20 Genes with Target Label')
plt.xlabel('Pearson Correlation Coefficient')
plt.ylabel('Gene ID (ID_REF)')
plt.tight_layout()
plt.show()

top_genes = gene_target_correlations.abs().sort_values(ascending=False).head(50).index

X_selected = X[top_genes]

print(X_selected.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_selected,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, predictions)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)

disp.plot()

plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_selected)

plt.figure(figsize=(8,6))

plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=y
)

plt.xlabel("PCA1")
plt.ylabel("PCA2")
plt.title("PCA of Cancer Gene Expression")

plt.show()

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Probability predictions
y_prob = model.predict_proba(X_test)[:,1]

# ROC values
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

# AUC score
roc_auc = auc(fpr, tpr)

# Plot ROC curve
plt.figure(figsize=(8,6))

plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")

plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("ROC Curve")

plt.legend()

plt.show()

import pandas as pd

importance = model.feature_importances_

feature_importance = pd.DataFrame({
    'Gene': X_selected.columns,
    'Importance': importance
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(feature_importance.head(20))

import matplotlib.pyplot as plt

top_features = feature_importance.head(20)

plt.figure(figsize=(10,8))

plt.barh(
    top_features['Gene'],
    top_features['Importance']
)

plt.xlabel("Importance")
plt.ylabel("Gene")

plt.title("Top Important Genes")

plt.gca().invert_yaxis()

plt.show()

import seaborn as sns

heatmap_data = X_selected[top_genes[:20]]

plt.figure(figsize=(12,8))

sns.heatmap(
    heatmap_data,
    cmap='viridis'
)

plt.title("Gene Expression Heatmap")

plt.show()

top_20_genes = feature_importance.head(20)

print(top_20_genes)

top_20_genes.to_csv(
    "top_20_genes.csv",
    index=False
)



from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model,
    X_selected,
    y,
    cv=5
)

print("Cross-validation scores:", scores)

print("Mean accuracy:", scores.mean())

from sklearn.svm import SVC

svm_model = SVC(probability=True)

svm_model.fit(X_train, y_train)

svm_predictions = svm_model.predict(X_test)
svm_accuracy = accuracy_score(
    y_test,
    svm_predictions
)

print("SVM Accuracy:", svm_accuracy)

plt.savefig("roc_curve.png")

feature_importance.to_csv(
    "feature_importance.csv",
    index=False
)